const config=JSON.parse(document.querySelector('#isblue-config')?.textContent||'{}');
const root=config.root||'/';
const money=n=>new Intl.NumberFormat(config.locale||'en-IN',{style:'currency',currency:config.currency||'INR',maximumFractionDigits:2}).format(n/100);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let opener=null,searchAbort=null,searchTimer=null;
const toast=message=>{const el=document.querySelector('[data-toast]');el.textContent=message;el.hidden=false;clearTimeout(el.timer);el.timer=setTimeout(()=>el.hidden=true,4500)};
function openDialog(id,source){const dialog=document.getElementById(id);if(!dialog)return;opener=source;dialog.showModal();if(id==='cart-dialog')loadCart();if(id==='search-dialog')dialog.querySelector('input').focus()}
document.addEventListener('click',event=>{
 const open=event.target.closest('[data-open]');if(open){event.preventDefault();openDialog(open.dataset.open,open)}
 const close=event.target.closest('[data-close]');if(close)close.closest('dialog').close();
 if(event.target.tagName==='DIALOG'){const r=event.target.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)event.target.close()}
 const quantity=event.target.closest('[data-quantity]');if(quantity){const input=quantity.parentElement.querySelector('input');input.value=Math.max(1,(Number(input.value)||1)+Number(quantity.dataset.quantity));input.dispatchEvent(new Event('change',{bubbles:true}))}
 const media=event.target.closest('[data-media-target]');if(media)showMedia(media.closest('[data-product-page]'),media.dataset.mediaTarget);
 const change=event.target.closest('[data-cart-change]');if(change)changeCart(change.dataset.key,Number(change.dataset.cartChange),change);
});
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',()=>opener?.focus()));
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.mega[open]').forEach(d=>d.open=false)});
document.addEventListener('click',e=>{if(!e.target.closest('.mega'))document.querySelectorAll('.mega[open]').forEach(d=>d.open=false)});
async function request(path,options={}){const response=await fetch(root+path,{...options,headers:{Accept:'application/json',...options.headers}});let data;try{data=await response.json()}catch{throw new Error('Something went wrong. Please try again.')}if(!response.ok)throw new Error(data.description||data.message||'We could not complete that. Please try again.');return data}
document.addEventListener('submit',async e=>{const form=e.target;if(!form.matches('[data-product-form]'))return;e.preventDefault();const button=form.querySelector('[type=submit]');const message=form.querySelector('.form-message');button.disabled=true;button.setAttribute('aria-busy','true');if(message)message.textContent='';try{await request('cart/add.js',{method:'POST',body:new FormData(form)});await loadCart();openDialog('cart-dialog',button);document.dispatchEvent(new CustomEvent('isblue:add-to-cart',{detail:{variantId:new FormData(form).get('id')}}))}catch(error){if(message)message.textContent=error.message;else toast(error.message)}finally{button.disabled=false;button.removeAttribute('aria-busy')}});
async function loadCart(){const target=document.querySelector('[data-cart-lines]');try{const cart=await request('cart.js');document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=cart.item_count);document.querySelector('[data-cart-total]').textContent=money(cart.total_price);document.querySelector('[data-cart-error]').textContent='';document.querySelector('.drawer-total').hidden=!cart.item_count;target.innerHTML=cart.items.length?cart.items.map(item=>`<article class="cart-line"><a href="${escape(item.url)}"><img src="${escape(item.image)}" alt="${escape(item.product_title)}" width="80" height="96"></a><div><h3><a href="${escape(item.url)}">${escape(item.product_title)}</a></h3>${item.variant_title&&item.variant_title!=='Default Title'?`<p>${escape(item.variant_title)}</p>`:''}<div class="quantity"><button data-cart-change="${item.quantity-1}" data-key="${escape(item.key)}" aria-label="Decrease quantity of ${escape(item.product_title)}">−</button><span aria-live="polite">${item.quantity}</span><button data-cart-change="${item.quantity+1}" data-key="${escape(item.key)}" aria-label="Increase quantity of ${escape(item.product_title)}">+</button></div><button class="remove-line" data-cart-change="0" data-key="${escape(item.key)}">Remove</button></div><strong class="cart-line-price">${money(item.final_line_price)}</strong></article>`).join(''):`<div class="empty-state"><h3>Room for something good.</h3><p>Your bag is empty. Let's find your next favourite.</p><a class="button button-primary" href="${root}collections/all">Explore the edit</a></div>`}catch(error){target.innerHTML='<p>Your bag could not be loaded.</p>';document.querySelector('[data-cart-error]').textContent=error.message}}
async function changeCart(key,quantity,button){document.querySelectorAll('[data-cart-change]').forEach(b=>b.disabled=true);try{await request('cart/change.js',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:key,quantity})});await loadCart()}catch(error){document.querySelector('[data-cart-error]').textContent=error.message;document.querySelectorAll('[data-cart-change]').forEach(b=>b.disabled=false)}}
document.addEventListener('input',e=>{if(!e.target.matches('[data-search-input]'))return;clearTimeout(searchTimer);searchAbort?.abort();const query=e.target.value.trim();const target=document.querySelector('[data-search-results]');if(query.length<2){target.innerHTML='<p class="search-hint">Try a pocket printer, a home upgrade, or your next travel essential.</p>';return}searchTimer=setTimeout(async()=>{searchAbort=new AbortController();target.innerHTML='<p class="search-hint">Finding the good stuff…</p>';try{const result=await request(`search/suggest.json?q=${encodeURIComponent(query)}&resources[type]=product&resources[limit]=5`,{signal:searchAbort.signal});const products=result.resources.results.products;target.innerHTML=products.length?products.map(p=>`<a class="search-result" href="${escape(p.url)}">${p.image?`<img src="${escape(typeof p.image==='string'?p.image:p.image.url)}" width="64" height="70" alt="">`:''}<div><h3>${escape(p.title)}</h3><span>View product</span></div></a>`).join(''):'<p class="search-hint">No matching finds. Try another search.</p>'}catch(error){if(error.name!=='AbortError')target.innerHTML='<p class="search-hint">Search suggestions are unavailable. Press Enter to see full results.</p>'}},250)});
function showMedia(page,id){page.querySelectorAll('[data-media-id]').forEach(el=>{el.hidden=el.dataset.mediaId!==String(id);el.querySelectorAll('video').forEach(v=>v.pause())});page.querySelectorAll('[data-media-target]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mediaTarget===String(id))))}
document.addEventListener('change',e=>{if(e.target.matches('[data-auto-submit]'))e.target.form.requestSubmit();if(e.target.matches('[data-variant-select]')){const page=e.target.closest('[data-product-page]');const variants=JSON.parse(page.querySelector('[data-variants]').textContent);const variant=variants.find(v=>String(v.id)===e.target.value);if(!variant)return;page.querySelector('[data-product-price]').textContent=money(variant.price);page.querySelector('[data-product-compare]').textContent=variant.compare_at_price>variant.price?money(variant.compare_at_price):'';const button=page.querySelector('[data-add-button]');button.disabled=!variant.available;button.textContent=variant.available?'Add to bag':'Sold out';if(variant.featured_media?.id)showMedia(page,variant.featured_media.id);const url=new URL(location.href);url.searchParams.set('variant',variant.id);history.replaceState({},'',url)}});
const motionContexts=new Map();
async function mountMotion(scope=document){
 if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
 const [{gsap},{ScrollTrigger}]=await Promise.all([import('gsap'),import('gsap/ScrollTrigger')]);gsap.registerPlugin(ScrollTrigger);
 scope.querySelectorAll('[data-motion-section]').forEach(section=>{
  if(motionContexts.has(section))return;
  const ctx=gsap.context(()=>{
   const targets=section.querySelectorAll(section.classList.contains('hero')?'.hero-copy>*':'.section-heading,.product-card,.category-tile,.spotlight-copy,.newsletter-form');
   if(targets.length)gsap.from(targets,{y:24,opacity:0,duration:.85,stagger:.07,ease:'power3.out',clearProps:'all',...(section.classList.contains('hero')?{}:{scrollTrigger:{trigger:section,start:'top 92%',once:true}})});
   const heading=section.querySelector('[data-word-reveal]');
   if(heading){heading.innerHTML=heading.textContent.trim().split(/\s+/).map(w=>`<span>${escape(w)}</span>`).join(' ');gsap.fromTo(heading.children,{opacity:.25},{opacity:1,stagger:.1,ease:'none',scrollTrigger:{trigger:heading,start:'top 85%',end:'bottom 45%',scrub:.7}})}
  },section);motionContexts.set(section,ctx);
 });
}
const effectCleanups=new Map();
async function mountEffects(scope=document){const targets=scope.querySelectorAll('[data-threeui]');if(!targets.length||matchMedia('(prefers-reduced-motion: reduce)').matches||navigator.connection?.saveData)return;try{const {mount}=await import('./threeui.js');targets.forEach(el=>{if(!effectCleanups.has(el))effectCleanups.set(el,mount(el))})}catch(error){console.info('IsBlue: static hero fallback active.',error)}}
const initialize=scope=>{mountMotion(scope).catch(()=>{});mountEffects(scope)};
initialize(document);
document.addEventListener('shopify:section:load',e=>initialize(e.target));
document.addEventListener('shopify:section:unload',e=>{motionContexts.forEach((ctx,el)=>{if(e.target.contains(el)){ctx.revert();motionContexts.delete(el)}});effectCleanups.forEach((cleanup,el)=>{if(e.target.contains(el)){cleanup();effectCleanups.delete(el)}})});
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{if(e.matches){motionContexts.forEach(ctx=>ctx.revert());motionContexts.clear();effectCleanups.forEach(cleanup=>cleanup());effectCleanups.clear()}else initialize(document)});
